version: '3'
services:
  redis:
    container_name: "redis"
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    container_name: "postgres"
    restart: always
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  cassandra:
    container_name: "cassandra"
    restart: always
    image: "cassandra:4"
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    volumes:
      - cassandra-data:/var/lib/cassandra
  nats:
    container_name: "nats"
    restart: always
    image: "nats:alpine"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      - NATS_USER=${NATS_USER}
      - NATS_PASSWORD=${NATS_PASSWORD}
    healthcheck:
      test: ["CMD", "nats", "tooling", "healthcheck", "nats://localhost:4222"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: {}
  cassandra-data: {}